# Generated by Django 5.1 on 2024-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='earn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='profit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='expense',
            field=models.IntegerField(null=True),
        ),
    ]
