# Generated by Django 5.1 on 2024-08-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_calendar_earn_calendar_profit_alter_calendar_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='profit',
        ),
    ]
